Python_Stack/Django/courses_project/apps/courses/urls.py
from django.conf.urls import url
from . import views

app_name = "courses"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add$', views.add, name='add'),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
    url(r'^delete/(?P<itemnum>\d+)$', views.delete, name='delete')
]

Python_Stack/Django/courses_project/courses_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.courses.urls'))
]

Python_Stack/Django/courses_project/apps/courses/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Course(models.Model):
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

Python_Stack/Django/courses_project/apps/courses/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Course
# Create your views here.

def index(request):
    context = {
    "names": Course.objects.all()
    }
    return render(request, "courses/index.html", context)

def add(request):
    Course.objects.create(name=request.POST['name'], description=request.POST['description'])
    return redirect('courses:index')

def destroy(request, id):
    context = {
    "item": Course.objects.filter(id=id)
    }
    return render(request, "courses/destroy.html", context)

def delete(request, itemnum):
    Course.objects.filter(id=itemnum).delete()
    return redirect('courses:index')

Python_Stack/Django/courses_project/apps/courses/templates/courses/destroy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Delete Section</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    {% for results in item %}
    <h2>Are you sure you want to delete the following course?</h2>
    <p>Name: {{results.name}}</p>
    <p>Description: {{results.description}}</p>
    <form action="{% url 'courses:index' %}" method="post">
      {% csrf_token %}
      <input type="submit" value="No">
    </form>
    <form action="{% url 'courses:delete' itemnum=results.id %}" method="post">
      {% csrf_token %}
      <input class="red" type="submit" value="Yes! I want to delete this">
    </form>
    {% endfor %}
  </body>
</html>

Python_Stack/Django/courses_project/apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Courses Assignment</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    <div id="container">
      <h1> Add a New Course</h1>
      <div id="adding">
        <form action="{% url 'courses:add' %}" method="post">
          {% csrf_token %}
          Name: <input type="text" name="name">
          <br>
          Description: <input type="text" name="description">
          <input class="green" type="submit" value="add">
        </form>
      </div>

      <div id="courses">
        <h2>Courses</h2>
        <table>
          <tr>
            <th>Course Name</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Actions</th>
          </tr>
          {% for results in names %}
          <tr>
            <td>{{ results.name }}</td>
            <td>{{ results.description }}</td>
            <td>{{ results.created_at }}</td>
            <td>
              <form class="button" action="{% url 'courses:destroy' id=results.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="remove">
              </form>
            </td>
          {% endfor %}
        </table>
      </div>
    </div>
  </body>
</html>